name: Deploy to Azure

on: push

env:
  AZURE_FUNCTIONS_ARTIFACT_NAME: azure-functions

jobs:
  deploy_infrastructure:
    name: Deploy Azure infrastructure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      RESOURCE_GROUP_NAME: ${{ steps.deploy_infrastructure.outputs.RESOURCE_GROUP_NAME }}
      FUNCTION_APP_NAME: ${{ steps.deploy_infrastructure.outputs.FUNCTION_APP_NAME }}
      STORAGE_ACCOUNT_NAME: ${{ steps.deploy_infrastructure.outputs.STORAGE_ACCOUNT_NAME }}
      STORAGE_ACCOUNT_FUNCTION_APP_CONTAINER_NAME: ${{ steps.deploy_infrastructure.outputs.STORAGE_ACCOUNT_FUNCTION_APP_CONTAINER_NAME }}
      STORAGE_ACCOUNT_FUNCTION_APP_PACKAGE_NAME: ${{ steps.deploy_infrastructure.outputs.STORAGE_ACCOUNT_FUNCTION_APP_PACKAGE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Deploy infrastructure
        id: deploy_infrastructure
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Set-StrictMode -Version Latest
            $ErrorActionPreference = "Stop"
            $VerbosePreference = "Continue"
            $InformationPreference = "Continue"

            $parameters = @{
              Name = "autodelete-deployment"
              Location = "eastus"
              TemplateFile = "${{ github.workspace }}/bicep/main.bicep"
              TemplateParameterObject = @{
                location = "eastus"
              }
            }
            $deployment = New-AzDeployment @parameters

            "RESOURCE_GROUP_NAME=$($deployment.Outputs.resourceGroupName.Value)" >> ${{ github.output }}
            "FUNCTION_APP_NAME=$($deployment.Outputs.functionAppName.Value)" >> ${{ github.output }}
            "STORAGE_ACCOUNT_NAME=$($deployment.Outputs.storageAccountName.Value)" >> ${{ github.output }}
            "STORAGE_ACCOUNT_FUNCTION_APP_CONTAINER_NAME=$($deployment.Outputs.storageAccountFunctionAppContainerName.Value)" >> ${{ github.output }}
            "STORAGE_ACCOUNT_FUNCTION_APP_PACKAGE_NAME=$($deployment.Outputs.storageAccountFunctionAppPackageName.Value)" >> ${{ github.output }}
          azPSVersion: 'latest'

  test:
    name: Test Azure function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Test Azure function
        run: |
          set -Eeuo pipefail
          dotnet test "${{ github.workspace }}/code/azurefunctions.tests/azurefunctions.tests.csproj"

  compile:
    name: Compile Azure function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Set output directory
        run: |
          echo "FUNCTION_OUTPUT_DIRECTORY=${{ runner.temp }}/functionoutput" >> ${{ github.env }}
      - name: Build Azure function
        run: |
          set -Eeuo pipefail
          dotnet publish "${{ github.workspace }}/code/azurefunctions/azurefunctions.csproj" --configuration Release --output "${{ env.FUNCTION_OUTPUT_DIRECTORY }}"
      - name: Save output
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.AZURE_FUNCTIONS_ARTIFACT_NAME }}
          path: ${{ env.FUNCTION_OUTPUT_DIRECTORY }}
          if-no-files-found: error
          retention-days: 1

  publish:
    name: Publish Azure function
    needs:
      - deploy_infrastructure
      - test
      - compile
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Set output directory
        run: |
          echo "FUNCTION_OUTPUT_DIRECTORY=${{ runner.temp }}/functionoutput" >> ${{ github.env }}
      - name: Download function artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.AZURE_FUNCTIONS_ARTIFACT_NAME }}
          path: ${{ env.FUNCTION_OUTPUT_DIRECTORY }}
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Upload package to storage account
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Set-StrictMode -Version Latest
            $ErrorActionPreference = "Stop"
            $VerbosePreference = "Continue"
            $InformationPreference = "Continue"

            $zipPath = Join-Path "${{ runner.temp }}" "functionoutput.zip"
            $compressParameters = @{
              Path = Join-Path ${{ env.FUNCTION_OUTPUT_DIRECTORY }} "*"
              DestinationPath = $zipPath
            }
            Compress-Archive @compressParameters
            
            $storageAccountParameters = @{
              Name = "${{ needs.deploy_infrastructure.outputs.STORAGE_ACCOUNT_NAME }}"
              ResourceGroupName = "${{ needs.deploy_infrastructure.outputs.RESOURCE_GROUP_NAME }}"
            }
            $storageAccountContext = Get-AzStorageAccount @storageAccountParameters | Select-Object -ExpandProperty "Context"
            
            $uploadParameters = @{
              File = $zipPath
              Blob = "${{ needs.deploy_infrastructure.outputs.STORAGE_ACCOUNT_FUNCTION_APP_PACKAGE_NAME }}"
              Container = "${{ needs.deploy_infrastructure.outputs.STORAGE_ACCOUNT_FUNCTION_APP_CONTAINER_NAME }}"
              Context = $storageAccountContext
            }
            Set-AzStorageBlobContent @uploadParameters
          azPSVersion: 'latest'
      - name: Restart function app
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Set-StrictMode -Version Latest
            $ErrorActionPreference = "Stop"
            $VerbosePreference = "Continue"
            $InformationPreference = "Continue"

            $restartParameters = @{
              Name = "${{ needs.deploy_infrastructure.outputs.FUNCTION_APP_NAME }}"
              ResourceGroupName = "${{ needs.deploy_infrastructure.outputs.RESOURCE_GROUP_NAME }}"
            }
            Restart-AzWebApp @restartParameters
          azPSVersion: 'latest'