name: Deploy to Azure

on: push

jobs:
  deploy_infrastructure:
    name: Deploy Azure infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Deploy infrastructure
        run: echo "Deploying infrastructure..."

  test:
    name: Test Azure function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Test Azure function
        run: |
          set -Eeuo pipefail
          dotnet test "${GITHUB_WORKSPACE}/code/azurefunctions.tests/azurefunctions.tests.csproj"

  compile:
    name: Compile Azure function
    runs-on: ubuntu-latest
    steps:
      - name: Compile Azure function
        run: echo "Compiling Azure function..."

  publish:
    name: Publish Azure function
    needs:
      - deploy_infrastructure
      - test
      - compile
    runs-on: ubuntu-latest
    steps:
      - name: Publish Azure function
        run: echo "Publishing Azure function..."